# SwiftLint Configuration for Koe

included:
  - KoeApp/Koe
  - Packages

excluded:
  - KoeApp/.build
  - Packages/*/.build

# Rule configuration
disabled_rules:
  - line_length  # Often impractical for SwiftUI code
  - function_body_length  # SwiftUI views can be long
  - type_body_length
  - file_length  # SwiftUI files can be longer

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - last_where
  - sorted_first_last
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - flatmap_over_map_reduce
  - closure_spacing
  - modifier_order
  - overridden_super_call
  - prohibited_super_call
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Customizations
identifier_name:
  min_length: 2
  excluded:
    - id
    - x
    - y
    - i
    - db

nesting:
  type_level: 3
  function_level: 3

type_name:
  min_length: 3
  max_length: 50

reporter: xcode
